language: node_js
node_js:
  - "6.9.0"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project satimage --token $FIREBASE_TOKEN
  - echo "Deployed!"
before_deploy: "echo 'ready?'"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "satimage"
after_deploy:
  - echo "Deployed!"